[package]
name = "knapsack_problem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.18.2"
rust_decimal = "1.33"
rust_decimal_macros = "1.33"

[dev-dependencies]
expectest = "0.12.0"